### ISSUE TITLE
Add support for multiple policies

### ISSUE THREAD

**Issue by claeyswo** [may-day/wsgicors#13]
As per the example this should be possible:

```

[filter:cors]
use = egg:wsgicors#middleware
policy=free
free_origin=copy
free_headers=*
free_expose_headers=*
free_methods=*
free_maxage=180

policy=subdom
subdom_origin=http://example.com http://example2.com https://*.example.com
subdom_headers=*
subdom_methods=*
subdom_expose_headers=Foo, Doom
subdom_maxage=180
```

However when I look at the code I don't see support for this implemented anywhere and when trying the above example only one policy takes effect. Am I missing something? If not is it possible to implement something like that?

**Comment by may-day** [comment]
My example was misleading. The intention was to decide at startup time which policy to use, so only one policy=... entry is in effect. I assume you interpreted it as depending on which origin matches a different policy is in use, right?

**Comment by claeyswo** [comment]
Exact. Would it be possible to implement something like that?

**Comment by may-day** [comment]
As long an origin doesn't match multiple policies i see no problem. What would you expect it to do if it matches multiple policies?

**Comment by claeyswo** [comment]
Our use case for example is that we want to be restrictive in the methods allowed for the general public and less restrictive if the request comes from one of our sub-domains:

``` java
origin = *.ourdomain.com
headers = *
methods = HEAD, OPTIONS, GET, POST, PUT, DELETE
```
``` java
origin = *
headers = *
methods = HEAD, OPTIONS, GET
```

Although as I am writing this I see the problem in what to do when it matches multiple policies. I thought about using the least restrictive if multiple match but then the question can be raised what is the least restrictive? In this example it is pretty straightforward but in a more complex situation with different allowed headers this isn't so clear anymore.

Another option would be to take the most specific match, i.e. a request with ``Origin: https://www.ourdomain.com`` has a more specific match to ``*.ourdomain.com`` than to ``*``

**Comment by may-day** [comment]
another would be to leave it to the programmer, like so: in your example the first policy is pol1 and the other is pol2.
You would be initialize the system with either
```
policy=pol1,pol2
``` 
or 
``` 
policy=pol2,pol1
``` 
let's call it the lazy approach

**Comment by may-day** [comment]
please try the "multipolicy" branch.
i've implemented the lazy approach (called "firstmatch")

as mentioned above you give an order by which policies are probed and the first that matches in that order becomes the active policy like so:
```
policy=pol1,pol2
```

**Comment by claeyswo** [comment]
Seems to work just fine. Thanks for the quick response and fix.
Could you merge and release this fix?

**Comment by may-day** [comment]
merged & released
