### ISSUE TITLE
CORS, postMessage, Twitter, JWT has left me in a spot

### ISSUE THREAD

**Issue by pauleveritt** [may-day/wsgicors#3]
Hi, I apologize as this is very obviously a plea for help, rather than a good bug report.

I've been working on ideas for a generic admin UI for Pyramid-based applications, written in AngularJS with JWT token auth. The idea is that the admin UI runs outside of the REST endpoint. In fact, it could manage multiple endpoints.

I've been stuck for a number of days on issues related to CORS. No amount of wiggling gets rid of: "SecurityError: Blocked a frame with origin "http://127.0.0.1:4220" from accessing a cross-origin frame." It's clear that I'm at an intersection of things that, when combined, I don't understand.

Any chance I could get some debugging help from you? I can give you the repo and write up something that does the best that I can to minimize the pain of getting it set up.

**Comment by MattSANU** [comment]
Hi Paul, assuming that the request you're doing is "GET http://somewhere/foo", and that it's coming from a script that was served from http://127.0.0.1:4220, then ensure that the response coming from http://somewhere/foo satisfies the following criteria:
1. Either:
1a. Has a header "Access-Control-Allow-Methods: GET"
or
1b. Has a header "Access-Control-Allow-Methods: *"
and
2. Either:
2a. Has a header "Access-Control-Allow-Origin: http://127.0.0.1:4220"
or
2b. Has a header "Access-Control-Allow-Origin: *"
and
3. If the request has any headers that are not in the list of 'safe' headers, then the response must have a header "Access-Control-Allow-Headers:", with value either all of the headers that weren't in that 'safe' list, or "*".
The list of 'safe' headers is in the CORS specification at: http://www.w3.org/TR/cors/
Hope this helps, Matt

**Comment by MattSANU** [comment]
Note the presence of the port in the Access-Control-Allow-Origin header. For the purposes of the Same Origin Policy, different ports on the same host are different origins. This threw me initially - I expected that the port wouldn't matter.

**Comment by MattSANU** [comment]
If you're still having problems, rather than supplying code, just supply the requests and responses which occur, if necessary by use of tcpdump.

**Comment by pauleveritt** [comment]
Sorry, I was on vacation and didn't see you make this reply. As a simplification, I have an HTML page served from nginx running on localhost (port 80). It has some jQuery which makes a POST to Pyramid running on port 6543.

This works:

free_headers=*

But any attempt to put in localhost fails. As a way to explain a little better, here's a narrated screencast of my setup: http://www.screencast.com/t/v9uSKpTB

This is of course a completely simple setup, so it is likely that I have forgotten something.

**Comment by pauleveritt** [comment]
Going into the debugger, at this line:

https://github.com/may-day/wsgicors/blob/master/wsgicors.py#L124

...orig == 'http://localhost' and self.pol_origin == 'localhost'. Those two don't match, leaving me with orig == None and I don't get me header appended.

Setting my origin to "http://localhost" fixed it:

    origin = "http://localhost"
    return CORS(config.make_wsgi_app(), headers="*", methods="*", maxage="180", origin=origin)

So perhaps there's some parsing that isn't working on getting the hostname out of the protocol?

**Comment by pauleveritt** [comment]
As a note, I'm running this under an old Pyramid (1.2.1) if that matters.

**Comment by may-day** [comment]
you actually are supposed to add a schema like http:// or https:// if you want to allow.
to allow any schema you can add something like: *://localhost
I clarified the example in the README.

**Comment by pauleveritt** [comment]
Yep, that was it, thanks.

—Paul

**Comment by MattSANU** [comment]
Hi Paul, yeah, the protocol has to be included, because a different protocol to the same hostname would still constitute a different 'origin'. See for example https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy
